version: "3" # composeファイルのバーション指定
services:
  app: # service名
    container_name: golang
    image: golang:latest
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    working_dir: /go/src/app
