version: "3" # composeファイルのバーション指定
services:
  app: # service名
    container_name: golang
    build: 
        context: .
        dockerfile: docker/GoDocker.dev
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
      # - golang-ssh:/root/.ssh
    

# volumes:
#   golang-ssh:
